# -*- coding: utf-8 -*-
"""Class Balancing Oversampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vihe9bhejz0xZkP9WvYWi_R3LpmMpIfS
"""

import numpy as np
import pandas as pd
import matplotlib as plt

df = pd.read_csv("/content/bank-full.csv", sep = ";")

df

df.shape

df.info(), df.describe()

df.columns

df = pd.get_dummies(df, columns=["default", "housing", "loan", "marital", "education", "contact", "poutcome"], dtype=int, sparse=True)

month_map = {
    'jan':1, 'feb':2, 'mar':3, 'apr':4,
    'may':5, 'jun':6, 'jul':7, 'aug':8,
    'sep':9, 'oct':10, 'nov':11, 'dec':12
}

df['month'] = df['month'].map(month_map)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df = df.drop("month", axis=1)

df['day_sin'] = np.sin(2 * np.pi * df['day'] / 12)
df['day_cos'] = np.cos(2 * np.pi * df['day'] / 12)

df = df.drop("day", axis=1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["y"]=le.fit_transform(df["y"])

from sklearn.preprocessing import TargetEncoder

TE = TargetEncoder()
df[["job"]] = TE.fit_transform(df[["job"]], df["y"])

df

x = df.drop("y", axis=1)
y = df["y"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaled = ['age', 'balance', 'duration', 'pdays', 'previous', 'month_sin', 'month_cos',
       'day_sin', 'day_cos']
ssc = StandardScaler()

x_train[scaled] = ssc.fit_transform(x_train[scaled])
x_test[scaled] = ssc.transform(x_test[scaled])

lr_classifier = LogisticRegression(class_weight='balanced')
lr_classifier.fit(x_train, y_train)
pred_lr_classifier = lr_classifier.predict(x_test)

g_nb = GaussianNB()
g_nb.fit(x_train, y_train)
pred_g_nb = g_nb.predict(x_test)

k_nn = KNeighborsClassifier()
k_nn.fit(x_train, y_train)
pred_k_nn = k_nn.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb = XGBClassifier(scale_pos_weight=ratio)
xgb.fit(x_train, y_train)
pred_xgb = xgb.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl.fit(x_train, y_train)
pred_rl_cl = rf_cl.predict(x_test)

ac_score_lr_cl = accuracy_score(y_test, pred_lr_classifier)
f1_score_lr_cl = f1_score(y_test, pred_lr_classifier)
pr_score_lr_cl = precision_score(y_test, pred_lr_classifier)
re_score_lr_cl = recall_score(y_test, pred_lr_classifier)

ac_score_rf_cl = accuracy_score(y_test, pred_rl_cl)
f1_score_rf_cl = f1_score(y_test, pred_rl_cl)
pr_score_rf_cl = precision_score(y_test, pred_rl_cl)
re_score_rf_cl = recall_score(y_test, pred_rl_cl)

Фac_score_g_nb = accuracy_score(y_test, pred_g_nb)
f1_score_g_nb = f1_score(y_test, pred_g_nb)
pr_score_g_nb = precision_score(y_test, pred_g_nb)
re_score_g_nb = recall_score(y_test, pred_g_nb)

ac_score_k_nn = accuracy_score(y_test, pred_k_nn)
f1_score_k_nn = f1_score(y_test, pred_k_nn)
pr_score_k_nn = precision_score(y_test, pred_k_nn)
re_score_k_nn = recall_score(y_test, pred_k_nn)

ac_score_xgb = accuracy_score(y_test, pred_xgb)
f1_score_xgb = f1_score(y_test, pred_xgb)
pr_score_xgb = precision_score(y_test, pred_xgb)
re_score_xgb = recall_score(y_test, pred_xgb)

table_classifier = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl, f1_score_lr_cl, pr_score_lr_cl, re_score_lr_cl],
    "RandomForest": [ac_score_rf_cl, f1_score_rf_cl, pr_score_rf_cl, re_score_rf_cl],
    "KNN": [ac_score_k_nn, f1_score_k_nn, pr_score_k_nn, re_score_k_nn],
    "XGBClassifier" : [ac_score_xgb, f1_score_xgb, pr_score_xgb, re_score_xgb]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier

!pip install imblearn

from imblearn.combine import SMOTEENN

smoteenn = SMOTEENN(random_state=42)
x_train_bal, y_train_bal = smoteenn.fit_resample(x_train, y_train)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

lr_classifier_smoteenn = LogisticRegression(class_weight='balanced')
lr_classifier_smoteenn.fit(x_train_bal, y_train_bal)
pred_lr_classifier_smoteenn = lr_classifier_smoteenn.predict(x_test)

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

ac_score_lr_cl_smoteenn = accuracy_score(y_test, pred_lr_classifier_smoteenn)
f1_score_lr_cl_smoteenn = f1_score(y_test, pred_lr_classifier_smoteenn)
pr_score_lr_cl_smoteenn = precision_score(y_test, pred_lr_classifier_smoteenn)
re_score_lr_cl_smoteenn = recall_score(y_test, pred_lr_classifier_smoteenn)

from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_smoteenn = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_smoteenn,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_smoteenn.fit(x_train_bal, y_train_bal)
pred_rl_cl_smoteenn = rf_cl_smoteenn.predict(x_test)

ac_score_rf_cl_smoteenn = accuracy_score(y_test, pred_rl_cl_smoteenn)
f1_score_rf_cl_smoteenn = f1_score(y_test, pred_rl_cl_smoteenn)
pr_score_rf_cl_smoteenn = precision_score(y_test, pred_rl_cl_smoteenn)
re_score_rf_cl_smoteenn = recall_score(y_test, pred_rl_cl_smoteenn)

g_nb_smoteenn = GaussianNB()
g_nb_smoteenn.fit(x_train_bal, y_train_bal)
pred_g_nb_smoteenn = g_nb_smoteenn.predict(x_test)

ac_score_g_nb_smoteenn = accuracy_score(y_test, pred_g_nb_smoteenn)
f1_score_g_nb_smoteenn = f1_score(y_test, pred_g_nb_smoteenn)
pr_score_g_nb_smoteenn = precision_score(y_test, pred_g_nb_smoteenn)
re_score_g_nb_smoteenn = recall_score(y_test, pred_g_nb_smoteenn)

k_nn_smoteenn = KNeighborsClassifier()
k_nn_smoteenn.fit(x_train_bal, y_train_bal)
pred_k_nn_smoteenn = k_nn_smoteenn.predict(x_test)

ac_score_k_nn_smoteenn = accuracy_score(y_test, pred_k_nn_smoteenn)
f1_score_k_nn_smoteenn = f1_score(y_test, pred_k_nn_smoteenn)
pr_score_k_nn_smoteenn = precision_score(y_test, pred_k_nn_smoteenn)
re_score_k_nn_smoteenn = recall_score(y_test, pred_k_nn_smoteenn)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_smoteenn = XGBClassifier(scale_pos_weight=ratio)
xgb_smoteenn.fit(x_train_bal, y_train_bal)
pred_xgb_smoteenn = xgb_smoteenn.predict(x_test)

ac_score_xgb_smoteenn = accuracy_score(y_test, pred_xgb_smoteenn)
f1_score_xgb_smoteenn = f1_score(y_test, pred_xgb_smoteenn)
pr_score_xgb_smoteenn = precision_score(y_test, pred_xgb_smoteenn)
re_score_xgb_smoteenn = recall_score(y_test, pred_xgb_smoteenn)

table_classifier_smoteenn = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_smoteenn, f1_score_lr_cl_smoteenn, pr_score_lr_cl_smoteenn, re_score_lr_cl_smoteenn],
    "RandomForest": [ac_score_rf_cl_smoteenn, f1_score_rf_cl_smoteenn, pr_score_rf_cl_smoteenn, re_score_rf_cl_smoteenn],
    "KNN": [ac_score_k_nn_smoteenn, f1_score_k_nn_smoteenn, pr_score_k_nn_smoteenn, re_score_k_nn_smoteenn],
    "XGBClassifier" : [ac_score_xgb_smoteenn, f1_score_xgb_smoteenn, pr_score_xgb_smoteenn, re_score_xgb_smoteenn]
}, index=["Accuracy", "F1", "Precision", "Recall"])

# Confusion matrix + табл метриков до и после балансировки

table_classifier_smoteenn

# балансировка датасета + SMOTE Class Balancing + FastApi ML + Deploy ML models + Streamlit gaid

!pip install imbalanced-learn

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
x_train_ro, y_train_ro = ros.fit_resample(x_train, y_train)

lr_classifier_ro = LogisticRegression(class_weight='balanced')
lr_classifier_ro.fit(x_train_ro, y_train_ro)
pred_lr_classifier_ro = lr_classifier_ro.predict(x_test)

g_nb_ro = GaussianNB()
g_nb_ro.fit(x_train_ro, y_train_ro)
pred_g_nb_ro = g_nb_ro.predict(x_test)

k_nn_ro = KNeighborsClassifier()
k_nn_ro.fit(x_train_ro, y_train_ro)
pred_k_nn_ro = k_nn_ro.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_ro = XGBClassifier(scale_pos_weight=ratio)
xgb_ro.fit(x_train_ro, y_train_ro)
pred_xgb_ro = xgb_ro.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_ro = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_ro,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_ro.fit(x_train_ro, y_train_ro)
pred_rl_cl_ro = rf_cl_ro.predict(x_test)

ac_score_lr_cl_ro = accuracy_score(y_test, pred_lr_classifier_ro)
f1_score_lr_cl_ro = f1_score(y_test, pred_lr_classifier_ro)
pr_score_lr_cl_ro = precision_score(y_test, pred_lr_classifier_ro)
re_score_lr_cl_ro = recall_score(y_test, pred_lr_classifier_ro)

ac_score_rf_cl_ro = accuracy_score(y_test, pred_rl_cl_ro)
f1_score_rf_cl_ro = f1_score(y_test, pred_rl_cl_ro)
pr_score_rf_cl_ro = precision_score(y_test, pred_rl_cl_ro)
re_score_rf_cl_ro = recall_score(y_test, pred_rl_cl_ro)

Фac_score_g_nb_ro = accuracy_score(y_test, pred_g_nb_ro)
f1_score_g_nb_ro = f1_score(y_test, pred_g_nb_ro)
pr_score_g_nb_ro = precision_score(y_test, pred_g_nb_ro)
re_score_g_nb_ro = recall_score(y_test, pred_g_nb_ro)

ac_score_k_nn_ro = accuracy_score(y_test, pred_k_nn_ro)
f1_score_k_nn_ro = f1_score(y_test, pred_k_nn_ro)
pr_score_k_nn_ro = precision_score(y_test, pred_k_nn_ro)
re_score_k_nn_ro = recall_score(y_test, pred_k_nn_ro)

ac_score_xgb_ro = accuracy_score(y_test, pred_xgb_ro)
f1_score_xgb_ro = f1_score(y_test, pred_xgb_ro)
pr_score_xgb_ro = precision_score(y_test, pred_xgb_ro)
re_score_xgb_ro = recall_score(y_test, pred_xgb_ro)

table_classifier_ro = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_ro, f1_score_lr_cl_ro, pr_score_lr_cl_ro, re_score_lr_cl_ro],
    "RandomForest": [ac_score_rf_cl_ro, f1_score_rf_cl_ro, pr_score_rf_cl_ro, re_score_rf_cl_ro],
    "KNN": [ac_score_k_nn_ro, f1_score_k_nn_ro, pr_score_k_nn_ro, re_score_k_nn_ro],
    "XGBClassifier" : [ac_score_xgb_ro, f1_score_xgb_ro, pr_score_xgb_ro, re_score_xgb_ro]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_ro

from imblearn.over_sampling import BorderlineSMOTE

border_smote = BorderlineSMOTE(kind="borderline-1", random_state=14)
x_train_border_smote, y_train_border_smote = border_smote.fit_resample(x_train, y_train)

lr_classifier_border_smote = LogisticRegression(class_weight='balanced')
lr_classifier_border_smote.fit(x_train_border_smote, y_train_border_smote)
pred_lr_classifier_border_smote = lr_classifier_border_smote.predict(x_test)

g_nb_border_smote = GaussianNB()
g_nb_border_smote.fit(x_train_border_smote, y_train_border_smote)
pred_g_nb_border_smote = g_nb_border_smote.predict(x_test)

k_nn_border_smote = KNeighborsClassifier()
k_nn_border_smote.fit(x_train_border_smote, y_train_border_smote)
pred_k_nn_border_smote = k_nn_border_smote.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_border_smote = XGBClassifier(scale_pos_weight=ratio)
xgb_border_smote.fit(x_train_border_smote, y_train_border_smote)
pred_xgb_border_smote = xgb_border_smote.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_border_smote = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_border_smote,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_border_smote.fit(x_train_border_smote, y_train_border_smote)
pred_rl_cl_border_smote = rf_cl_border_smote.predict(x_test)

ac_score_lr_cl_border_smote = accuracy_score(y_test, pred_lr_classifier_border_smote)
f1_score_lr_cl_border_smote = f1_score(y_test, pred_lr_classifier_border_smote)
pr_score_lr_cl_border_smote = precision_score(y_test, pred_lr_classifier_border_smote)
re_score_lr_cl_border_smote = recall_score(y_test, pred_lr_classifier_border_smote)

ac_score_rf_cl_border_smote = accuracy_score(y_test, pred_rl_cl_border_smote)
f1_score_rf_cl_border_smote = f1_score(y_test, pred_rl_cl_border_smote)
pr_score_rf_cl_border_smote = precision_score(y_test, pred_rl_cl_border_smote)
re_score_rf_cl_border_smote = recall_score(y_test, pred_rl_cl_border_smote)

Фac_score_g_nb_border_smote = accuracy_score(y_test, pred_g_nb_border_smote)
f1_score_g_nb_border_smote = f1_score(y_test, pred_g_nb_border_smote)
pr_score_g_nb_border_smote = precision_score(y_test, pred_g_nb_border_smote)
re_score_g_nb_border_smote = recall_score(y_test, pred_g_nb_border_smote)

ac_score_k_nn_border_smote = accuracy_score(y_test, pred_k_nn_border_smote)
f1_score_k_nn_border_smote = f1_score(y_test, pred_k_nn_border_smote)
pr_score_k_nn_border_smote = precision_score(y_test, pred_k_nn_border_smote)
re_score_k_nn_border_smote = recall_score(y_test, pred_k_nn_border_smote)

ac_score_xgb_border_smote = accuracy_score(y_test, pred_xgb_border_smote)
f1_score_xgb_border_smote = f1_score(y_test, pred_xgb_border_smote)
pr_score_xgb_border_smote = precision_score(y_test, pred_xgb_border_smote)
re_score_xgb_border_smote = recall_score(y_test, pred_xgb_border_smote)

table_classifier_border_smote = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_border_smote, f1_score_lr_cl_border_smote, pr_score_lr_cl_border_smote, re_score_lr_cl_border_smote],
    "RandomForest": [ac_score_rf_cl_border_smote, f1_score_rf_cl_border_smote, pr_score_rf_cl_border_smote, re_score_rf_cl_border_smote],
    "KNN": [ac_score_k_nn_border_smote, f1_score_k_nn_border_smote, pr_score_k_nn_border_smote, re_score_k_nn_border_smote],
    "XGBClassifier" : [ac_score_xgb_border_smote, f1_score_xgb_border_smote, pr_score_xgb_border_smote, re_score_xgb_border_smote]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_border_smote

"""
# Methods of Oversampling
"""

# Without oversampling for comparing
table_classifier

table_classifier_ro

table_classifier_border_smote

table_classifier_smoteenn

!shap

import shap

x_background = x_train.sample(100, random_state=42)
def f(X):
    return xgb.predict_proba(X)[:, 1]

explainer = shap.Explainer(f, x_background)
shap_values = explainer(x_test)

x_test_sample = x_test.iloc[:20]

shap_values = explainer.shap_values(x_test_sample)

sv = np.array(shap_values)
if len(sv.shape) == 3:
  if sv.shape[0] == x_test_sample.shape[0]:
    shap_class_1 = sv[:, :, 1]
  else:
    shap_class_1 = sv[1]
else:
  shap_class_1 = sv

shap.summary_plot(shap_class_1, x_test_sample, plot_type="bar")

shap.summary_plot(shap_class_1, x_test_sample)

# + методы балансировки + андерсемплинг +- 3-4 по каждому виду + комбинированные

# возможность добавления файла в стримлит + выбор какую балансировку брать + визуализация методов и сравнение по визуализации -> кнопка для сравнение метрик