# -*- coding: utf-8 -*-
"""Class Balancing Undersampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8Q9d3wLTAUkE7IvM7wvvfIrdgMx0hq8
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/bank-full.csv", sep=";")

df

df = pd.get_dummies(df, columns=["default", "housing", "loan", "marital", "education", "contact", "poutcome"], dtype=int, sparse=True)

month_map = {
    'jan':1, 'feb':2, 'mar':3, 'apr':4,
    'may':5, 'jun':6, 'jul':7, 'aug':8,
    'sep':9, 'oct':10, 'nov':11, 'dec':12
}

df['month'] = df['month'].map(month_map)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df = df.drop("month", axis=1)

df['day_sin'] = np.sin(2 * np.pi * df['day'] / 12)
df['day_cos'] = np.cos(2 * np.pi * df['day'] / 12)

df = df.drop("day", axis=1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["y"]=le.fit_transform(df["y"])

from sklearn.preprocessing import TargetEncoder

TE = TargetEncoder()
df[["job"]] = TE.fit_transform(df[["job"]], df["y"])

df

x = df.drop("y", axis=1)
y = df["y"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaled = ['age', 'balance', 'duration', 'pdays', 'previous', 'month_sin', 'month_cos',
       'day_sin', 'day_cos']
ssc = StandardScaler()

x_train[scaled] = ssc.fit_transform(x_train[scaled])
x_test[scaled] = ssc.transform(x_test[scaled])

! pip install xgboost

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import RandomizedSearchCV

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

lr_classifier = LogisticRegression(class_weight='balanced')
lr_classifier.fit(x_train, y_train)
pred_lr_classifier = lr_classifier.predict(x_test)

g_nb = GaussianNB()
g_nb.fit(x_train, y_train)
pred_g_nb = g_nb.predict(x_test)

k_nn = KNeighborsClassifier()
k_nn.fit(x_train, y_train)
pred_k_nn = k_nn.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb = XGBClassifier(scale_pos_weight=ratio)
xgb.fit(x_train, y_train)
pred_xgb = xgb.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl.fit(x_train, y_train)
pred_rl_cl = rf_cl.predict(x_test)

ac_score_lr_cl = accuracy_score(y_test, pred_lr_classifier)
f1_score_lr_cl = f1_score(y_test, pred_lr_classifier)
pr_score_lr_cl = precision_score(y_test, pred_lr_classifier)
re_score_lr_cl = recall_score(y_test, pred_lr_classifier)

ac_score_rf_cl = accuracy_score(y_test, pred_rl_cl)
f1_score_rf_cl = f1_score(y_test, pred_rl_cl)
pr_score_rf_cl = precision_score(y_test, pred_rl_cl)
re_score_rf_cl = recall_score(y_test, pred_rl_cl)

Фac_score_g_nb = accuracy_score(y_test, pred_g_nb)
f1_score_g_nb = f1_score(y_test, pred_g_nb)
pr_score_g_nb = precision_score(y_test, pred_g_nb)
re_score_g_nb = recall_score(y_test, pred_g_nb)

ac_score_k_nn = accuracy_score(y_test, pred_k_nn)
f1_score_k_nn = f1_score(y_test, pred_k_nn)
pr_score_k_nn = precision_score(y_test, pred_k_nn)
re_score_k_nn = recall_score(y_test, pred_k_nn)

ac_score_xgb = accuracy_score(y_test, pred_xgb)
f1_score_xgb = f1_score(y_test, pred_xgb)
pr_score_xgb = precision_score(y_test, pred_xgb)
re_score_xgb = recall_score(y_test, pred_xgb)

table_classifier = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl, f1_score_lr_cl, pr_score_lr_cl, re_score_lr_cl],
    "RandomForest": [ac_score_rf_cl, f1_score_rf_cl, pr_score_rf_cl, re_score_rf_cl],
    "KNN": [ac_score_k_nn, f1_score_k_nn, pr_score_k_nn, re_score_k_nn],
    "XGBClassifier" : [ac_score_xgb, f1_score_xgb, pr_score_xgb, re_score_xgb]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier

!pip install imblearn

from imblearn.under_sampling import RandomUnderSampler

r_u = RandomUnderSampler(random_state=14)
x_train_r_u, y_train_r_u = r_u.fit_resample(x_train, y_train)

lr_classifier_r_u = LogisticRegression(class_weight='balanced')
lr_classifier_r_u.fit(x_train_r_u, y_train_r_u)
pred_lr_classifier_r_u = lr_classifier_r_u.predict(x_test)

g_nb_r_u = GaussianNB()
g_nb_r_u.fit(x_train_r_u, y_train_r_u)
pred_g_nb_r_u = g_nb_r_u.predict(x_test)

k_nn_r_u = KNeighborsClassifier()
k_nn_r_u.fit(x_train_r_u, y_train_r_u)
pred_k_nn_r_u = k_nn_r_u.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_r_u = XGBClassifier(scale_pos_weight=ratio)
xgb_r_u.fit(x_train_r_u, y_train_r_u)
pred_xgb_r_u = xgb_r_u.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3]
}

rf_cl_r_u = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_r_u,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_r_u.fit(x_train_r_u, y_train_r_u)
pred_rl_cl_r_u = rf_cl_r_u.predict(x_test)

ac_score_lr_cl_r_u = accuracy_score(y_test, pred_lr_classifier_r_u)
f1_score_lr_cl_r_u = f1_score(y_test, pred_lr_classifier_r_u)
pr_score_lr_cl_r_u = precision_score(y_test, pred_lr_classifier_r_u)
re_score_lr_cl_r_u = recall_score(y_test, pred_lr_classifier_r_u)

ac_score_rf_cl_r_u = accuracy_score(y_test, pred_rl_cl_r_u)
f1_score_rf_cl_r_u = f1_score(y_test, pred_rl_cl_r_u)
pr_score_rf_cl_r_u = precision_score(y_test, pred_rl_cl_r_u)
re_score_rf_cl_r_u = recall_score(y_test, pred_rl_cl_r_u)

ac_score_g_nb_r_u = accuracy_score(y_test, pred_g_nb_r_u)
f1_score_g_nb_r_u = f1_score(y_test, pred_g_nb_r_u)
pr_score_g_nb_r_u = precision_score(y_test, pred_g_nb_r_u)
re_score_g_nb_r_u = recall_score(y_test, pred_g_nb_r_u)

ac_score_k_nn_r_u = accuracy_score(y_test, pred_k_nn_r_u)
f1_score_k_nn_r_u = f1_score(y_test, pred_k_nn_r_u)
pr_score_k_nn_r_u = precision_score(y_test, pred_k_nn_r_u)
re_score_k_nn_r_u = recall_score(y_test, pred_k_nn_r_u)

ac_score_xgb_r_u = accuracy_score(y_test, pred_xgb_r_u)
f1_score_xgb_r_u = f1_score(y_test, pred_xgb_r_u)
pr_score_xgb_r_u = precision_score(y_test, pred_xgb_r_u)
re_score_xgb_r_u = recall_score(y_test, pred_xgb_r_u)

table_classifier_r_u = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_r_u, f1_score_lr_cl_r_u, pr_score_lr_cl_r_u, re_score_lr_cl_r_u],
    "RandomForest": [ac_score_rf_cl_r_u, f1_score_rf_cl_r_u, pr_score_rf_cl_r_u, re_score_rf_cl_r_u],
    "KNN": [ac_score_k_nn_r_u, f1_score_k_nn_r_u, pr_score_k_nn_r_u, re_score_k_nn_r_u],
    "XGBClassifier" : [ac_score_xgb_r_u, f1_score_xgb_r_u, pr_score_xgb_r_u, re_score_xgb_r_u]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_r_u

from imblearn.under_sampling import NearMiss

nm = NearMiss()
x_train_nm, y_train_nm = nm.fit_resample(x_train, y_train)

lr_classifier_nm = LogisticRegression(class_weight='balanced')
lr_classifier_nm.fit(x_train_nm, y_train_nm)
pred_lr_classifier_nm = lr_classifier_nm.predict(x_test)

g_nb_nm = GaussianNB()
g_nb_nm.fit(x_train_nm, y_train_nm)
pred_g_nb_nm = g_nb_nm.predict(x_test)

k_nn_nm = KNeighborsClassifier()
k_nn_nm.fit(x_train_nm, y_train_nm)
pred_k_nn_nm = k_nn_nm.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_nm = XGBClassifier(scale_pos_weight=ratio)
xgb_nm.fit(x_train_nm, y_train_nm)
pred_xgb_nm = xgb_nm.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_nm = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_nm,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_nm.fit(x_train_nm, y_train_nm)
pred_rl_cl_nm = rf_cl_nm.predict(x_test)

ac_score_lr_cl_nm = accuracy_score(y_test, pred_lr_classifier_nm)
f1_score_lr_cl_nm = f1_score(y_test, pred_lr_classifier_nm)
pr_score_lr_cl_nm = precision_score(y_test, pred_lr_classifier_nm)
re_score_lr_cl_nm = recall_score(y_test, pred_lr_classifier_nm)

ac_score_rf_cl_nm = accuracy_score(y_test, pred_rl_cl_nm)
f1_score_rf_cl_nm = f1_score(y_test, pred_rl_cl_nm)
pr_score_rf_cl_nm = precision_score(y_test, pred_rl_cl_nm)
re_score_rf_cl_nm = recall_score(y_test, pred_rl_cl_nm)

Фac_score_g_nb_nm = accuracy_score(y_test, pred_g_nb_nm)
f1_score_g_nb_nm = f1_score(y_test, pred_g_nb_nm)
pr_score_g_nb_nm = precision_score(y_test, pred_g_nb_nm)
re_score_g_nb_nm = recall_score(y_test, pred_g_nb_nm)

ac_score_k_nn_nm = accuracy_score(y_test, pred_k_nn_nm)
f1_score_k_nn_nm = f1_score(y_test, pred_k_nn_nm)
pr_score_k_nn_nm = precision_score(y_test, pred_k_nn_nm)
re_score_k_nn_nm = recall_score(y_test, pred_k_nn_nm)

ac_score_xgb_nm = accuracy_score(y_test, pred_xgb_nm)
f1_score_xgb_nm = f1_score(y_test, pred_xgb_nm)
pr_score_xgb_nm = precision_score(y_test, pred_xgb_nm)
re_score_xgb_nm = recall_score(y_test, pred_xgb_nm)

table_classifier_nm = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_nm, f1_score_lr_cl_nm, pr_score_lr_cl_nm, re_score_lr_cl_nm],
    "RandomForest": [ac_score_rf_cl_nm, f1_score_rf_cl_nm, pr_score_rf_cl_nm, re_score_rf_cl_nm],
    "KNN": [ac_score_k_nn_nm, f1_score_k_nn_nm, pr_score_k_nn_nm, re_score_k_nn_nm],
    "XGBClassifier" : [ac_score_xgb_nm, f1_score_xgb_nm, pr_score_xgb_nm, re_score_xgb_nm]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_nm

from imblearn.under_sampling import TomekLinks

tlinks = TomekLinks()
x_train_tlinks, y_train_tlinks = tlinks.fit_resample(x_train, y_train)

lr_classifier_tlinks = LogisticRegression(class_weight='balanced')
lr_classifier_tlinks.fit(x_train_tlinks, y_train_tlinks)
pred_lr_classifier_tlinks = lr_classifier_tlinks.predict(x_test)

g_nb_tlinks = GaussianNB()
g_nb_tlinks.fit(x_train_tlinks, y_train_tlinks)
pred_g_nb_tlinks = g_nb_tlinks.predict(x_test)

k_nn_tlinks = KNeighborsClassifier()
k_nn_tlinks.fit(x_train_tlinks, y_train_tlinks)
pred_k_nn_tlinks = k_nn_tlinks.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_tlinks = XGBClassifier(scale_pos_weight=ratio)
xgb_tlinks.fit(x_train_tlinks, y_train_tlinks)
pred_xgb_tlinks = xgb_tlinks.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_tlinks = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_tlinks,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_tlinks.fit(x_train_tlinks, y_train_tlinks)
pred_rl_cl_tlinks = rf_cl_tlinks.predict(x_test)

ac_score_lr_cl_tlinks = accuracy_score(y_test, pred_lr_classifier_tlinks)
f1_score_lr_cl_tlinks = f1_score(y_test, pred_lr_classifier_tlinks)
pr_score_lr_cl_tlinks = precision_score(y_test, pred_lr_classifier_tlinks)
re_score_lr_cl_tlinks = recall_score(y_test, pred_lr_classifier_tlinks)

ac_score_rf_cl_tlinks = accuracy_score(y_test, pred_rl_cl_tlinks)
f1_score_rf_cl_tlinks = f1_score(y_test, pred_rl_cl_tlinks)
pr_score_rf_cl_tlinks = precision_score(y_test, pred_rl_cl_tlinks)
re_score_rf_cl_tlinks = recall_score(y_test, pred_rl_cl_tlinks)

Фac_score_g_nb_tlinks = accuracy_score(y_test, pred_g_nb_tlinks)
f1_score_g_nb_tlinks = f1_score(y_test, pred_g_nb_tlinks)
pr_score_g_nb_tlinks = precision_score(y_test, pred_g_nb_tlinks)
re_score_g_nb_tlinks = recall_score(y_test, pred_g_nb_tlinks)

ac_score_k_nn_tlinks = accuracy_score(y_test, pred_k_nn_tlinks)
f1_score_k_nn_tlinks = f1_score(y_test, pred_k_nn_tlinks)
pr_score_k_nn_tlinks = precision_score(y_test, pred_k_nn_tlinks)
re_score_k_nn_tlinks = recall_score(y_test, pred_k_nn_tlinks)

ac_score_xgb_tlinks = accuracy_score(y_test, pred_xgb_tlinks)
f1_score_xgb_tlinks = f1_score(y_test, pred_xgb_tlinks)
pr_score_xgb_tlinks = precision_score(y_test, pred_xgb_tlinks)
re_score_xgb_tlinks = recall_score(y_test, pred_xgb_tlinks)

table_classifier_tlinks = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_tlinks, f1_score_lr_cl_tlinks, pr_score_lr_cl_tlinks, re_score_lr_cl_tlinks],
    "RandomForest": [ac_score_rf_cl_tlinks, f1_score_rf_cl_tlinks, pr_score_rf_cl_tlinks, re_score_rf_cl_tlinks],
    "KNN": [ac_score_k_nn_tlinks, f1_score_k_nn_tlinks, pr_score_k_nn_tlinks, re_score_k_nn_tlinks],
    "XGBClassifier" : [ac_score_xgb_tlinks, f1_score_xgb_tlinks, pr_score_xgb_tlinks, re_score_xgb_tlinks]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_tlinks

"""# Methods of Undersampling"""

# Without oversampling for comparing
table_classifier

table_classifier_r_u

table_classifier_nm

table_classifier_tlinks