# -*- coding: utf-8 -*-
"""Class Balancing Combined Resampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHD1IrCO3bta0N7bt1WDPPUlKTgqCL6r
"""

import numpy as np
import pandas as pd
import matplotlib as plt

df = pd.read_csv("/content/bank-full.csv", sep = ";")

df

df.shape

df.info(), df.describe()

df.columns

df = pd.get_dummies(df, columns=["default", "housing", "loan", "marital", "education", "contact", "poutcome"], dtype=int, sparse=True)

month_map = {
    'jan':1, 'feb':2, 'mar':3, 'apr':4,
    'may':5, 'jun':6, 'jul':7, 'aug':8,
    'sep':9, 'oct':10, 'nov':11, 'dec':12
}

df['month'] = df['month'].map(month_map)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df = df.drop("month", axis=1)

df['day_sin'] = np.sin(2 * np.pi * df['day'] / 12)
df['day_cos'] = np.cos(2 * np.pi * df['day'] / 12)

df = df.drop("day", axis=1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["y"]=le.fit_transform(df["y"])

from sklearn.preprocessing import TargetEncoder

TE = TargetEncoder()
df[["job"]] = TE.fit_transform(df[["job"]], df["y"])

df

x = df.drop("y", axis=1)
y = df["y"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaled = ['age', 'balance', 'duration', 'pdays', 'previous', 'month_sin', 'month_cos',
       'day_sin', 'day_cos']
ssc = StandardScaler()

x_train[scaled] = ssc.fit_transform(x_train[scaled])
x_test[scaled] = ssc.transform(x_test[scaled])

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

lr_classifier = LogisticRegression(class_weight='balanced')
lr_classifier.fit(x_train, y_train)
pred_lr_classifier = lr_classifier.predict(x_test)

g_nb = GaussianNB()
g_nb.fit(x_train, y_train)
pred_g_nb = g_nb.predict(x_test)

k_nn = KNeighborsClassifier()
k_nn.fit(x_train, y_train)
pred_k_nn = k_nn.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb = XGBClassifier(scale_pos_weight=ratio)
xgb.fit(x_train, y_train)
pred_xgb = xgb.predict(x_test)

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl.fit(x_train, y_train)
pred_rl_cl = rf_cl.predict(x_test)

ac_score_lr_cl = accuracy_score(y_test, pred_lr_classifier)
f1_score_lr_cl = f1_score(y_test, pred_lr_classifier)
pr_score_lr_cl = precision_score(y_test, pred_lr_classifier)
re_score_lr_cl = recall_score(y_test, pred_lr_classifier)

ac_score_rf_cl = accuracy_score(y_test, pred_rl_cl)
f1_score_rf_cl = f1_score(y_test, pred_rl_cl)
pr_score_rf_cl = precision_score(y_test, pred_rl_cl)
re_score_rf_cl = recall_score(y_test, pred_rl_cl)

Фac_score_g_nb = accuracy_score(y_test, pred_g_nb)
f1_score_g_nb = f1_score(y_test, pred_g_nb)
pr_score_g_nb = precision_score(y_test, pred_g_nb)
re_score_g_nb = recall_score(y_test, pred_g_nb)

ac_score_k_nn = accuracy_score(y_test, pred_k_nn)
f1_score_k_nn = f1_score(y_test, pred_k_nn)
pr_score_k_nn = precision_score(y_test, pred_k_nn)
re_score_k_nn = recall_score(y_test, pred_k_nn)

ac_score_xgb = accuracy_score(y_test, pred_xgb)
f1_score_xgb = f1_score(y_test, pred_xgb)
pr_score_xgb = precision_score(y_test, pred_xgb)
re_score_xgb = recall_score(y_test, pred_xgb)

table_classifier = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl, f1_score_lr_cl, pr_score_lr_cl, re_score_lr_cl],
    "RandomForest": [ac_score_rf_cl, f1_score_rf_cl, pr_score_rf_cl, re_score_rf_cl],
    "KNN": [ac_score_k_nn, f1_score_k_nn, pr_score_k_nn, re_score_k_nn],
    "XGBClassifier" : [ac_score_xgb, f1_score_xgb, pr_score_xgb, re_score_xgb]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier

!pip install imblearn

from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek

smt = SMOTETomek(smote=SMOTE(k_neighbors=3), random_state=42)
x_train_smt, y_train_smt = smt.fit_resample(x_train, y_train)

lr_classifier_smt = LogisticRegression(class_weight='balanced')
lr_classifier_smt.fit(x_train_smt, y_train_smt)
pred_lr_classifier_smt = lr_classifier_smt.predict(x_test)

g_nb_smt = GaussianNB()
g_nb_smt.fit(x_train_smt, y_train_smt)
pred_g_nb_smt = g_nb_smt.predict(x_test)

k_nn_smt = KNeighborsClassifier()
k_nn_smt.fit(x_train_smt, y_train_smt)
pred_k_nn_smt = k_nn_smt.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_smt = XGBClassifier(scale_pos_weight=ratio)
xgb_smt.fit(x_train_smt, y_train_smt)
pred_xgb_smt = xgb_smt.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_smt = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_smt,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_smt.fit(x_train_smt, y_train_smt)
pred_rl_cl_smt = rf_cl_smt.predict(x_test)

ac_score_lr_cl_smt = accuracy_score(y_test, pred_lr_classifier_smt)
f1_score_lr_cl_smt = f1_score(y_test, pred_lr_classifier_smt)
pr_score_lr_cl_smt = precision_score(y_test, pred_lr_classifier_smt)
re_score_lr_cl_smt = recall_score(y_test, pred_lr_classifier_smt)

ac_score_rf_cl_smt = accuracy_score(y_test, pred_rl_cl_smt)
f1_score_rf_cl_smt = f1_score(y_test, pred_rl_cl_smt)
pr_score_rf_cl_smt = precision_score(y_test, pred_rl_cl_smt)
re_score_rf_cl_smt = recall_score(y_test, pred_rl_cl_smt)

ac_score_g_nb_smt = accuracy_score(y_test, pred_g_nb_smt)
f1_score_g_nb_smt = f1_score(y_test, pred_g_nb_smt)
pr_score_g_nb_smt = precision_score(y_test, pred_g_nb_smt)
re_score_g_nb_smt = recall_score(y_test, pred_g_nb_smt)

ac_score_k_nn_smt = accuracy_score(y_test, pred_k_nn_smt)
f1_score_k_nn_smt = f1_score(y_test, pred_k_nn_smt)
pr_score_k_nn_smt = precision_score(y_test, pred_k_nn_smt)
re_score_k_nn_smt = recall_score(y_test, pred_k_nn_smt)

ac_score_xgb_smt = accuracy_score(y_test, pred_xgb_smt)
f1_score_xgb_smt = f1_score(y_test, pred_xgb_smt)
pr_score_xgb_smt = precision_score(y_test, pred_xgb_smt)
re_score_xgb_smt = recall_score(y_test, pred_xgb_smt)

table_classifier_smt = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_smt, f1_score_lr_cl_smt, pr_score_lr_cl_smt, re_score_lr_cl_smt],
    "RandomForest": [ac_score_rf_cl_smt, f1_score_rf_cl_smt, pr_score_rf_cl_smt, re_score_rf_cl_smt],
    "KNN": [ac_score_k_nn_smt, f1_score_k_nn_smt, pr_score_k_nn_smt, re_score_k_nn_smt],
    "XGBClassifier" : [ac_score_xgb_smt, f1_score_xgb_smt, pr_score_xgb_smt, re_score_xgb_smt]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_smt

from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN

smeen = SMOTETomek(smote=SMOTE(k_neighbors=3), random_state=42)
x_train_smeen, y_train_smeen = smeen.fit_resample(x_train, y_train)

lr_classifier_smeen = LogisticRegression(class_weight='balanced')
lr_classifier_smeen.fit(x_train_smeen, y_train_smeen)
pred_lr_classifier_smeen = lr_classifier_smeen.predict(x_test)

g_nb_smeen = GaussianNB()
g_nb_smeen.fit(x_train_smeen, y_train_smeen)
pred_g_nb_smeen = g_nb_smeen.predict(x_test)

k_nn_smeen = KNeighborsClassifier()
k_nn_smeen.fit(x_train_smeen, y_train_smeen)
pred_k_nn_smeen = k_nn_smeen.predict(x_test)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

ratio = neg / pos

# class_weight = balanced scale_plus_weight - для xgb
xgb_smeen = XGBClassifier(scale_pos_weight=ratio)
xgb_smeen.fit(x_train_smeen, y_train_smeen)
pred_xgb_smeen = xgb_smeen.predict(x_test)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [1, 3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.3],
    'class_weight': ['balanced', 'balanced_subsample']
}

rf_cl_smeen = RandomForestClassifier(random_state=42, n_jobs=-16, class_weight='balanced')
search = RandomizedSearchCV(
    rf_cl_smeen,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_cl_smeen.fit(x_train_smeen, y_train_smeen)
pred_rl_cl_smeen = rf_cl_smeen.predict(x_test)

ac_score_lr_cl_smeen = accuracy_score(y_test, pred_lr_classifier_smeen)
f1_score_lr_cl_smeen = f1_score(y_test, pred_lr_classifier_smeen)
pr_score_lr_cl_smeen = precision_score(y_test, pred_lr_classifier_smeen)
re_score_lr_cl_smeen = recall_score(y_test, pred_lr_classifier_smeen)

ac_score_rf_cl_smeen = accuracy_score(y_test, pred_rl_cl_smeen)
f1_score_rf_cl_smeen = f1_score(y_test, pred_rl_cl_smeen)
pr_score_rf_cl_smeen = precision_score(y_test, pred_rl_cl_smeen)
re_score_rf_cl_smeen = recall_score(y_test, pred_rl_cl_smeen)

ac_score_g_nb_smeen = accuracy_score(y_test, pred_g_nb_smeen)
f1_score_g_nb_smeen = f1_score(y_test, pred_g_nb_smeen)
pr_score_g_nb_smeen = precision_score(y_test, pred_g_nb_smeen)
re_score_g_nb_smeen = recall_score(y_test, pred_g_nb_smeen)

ac_score_k_nn_smeen = accuracy_score(y_test, pred_k_nn_smeen)
f1_score_k_nn_smeen = f1_score(y_test, pred_k_nn_smeen)
pr_score_k_nn_smeen = precision_score(y_test, pred_k_nn_smeen)
re_score_k_nn_smeen = recall_score(y_test, pred_k_nn_smeen)

ac_score_xgb_smeen = accuracy_score(y_test, pred_xgb_smeen)
f1_score_xgb_smeen = f1_score(y_test, pred_xgb_smeen)
pr_score_xgb_smeen = precision_score(y_test, pred_xgb_smeen)
re_score_xgb_smeen = recall_score(y_test, pred_xgb_smeen)

table_classifier_smeen = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl_smeen, f1_score_lr_cl_smeen, pr_score_lr_cl_smeen, re_score_lr_cl_smeen],
    "RandomForest": [ac_score_rf_cl_smeen, f1_score_rf_cl_smeen, pr_score_rf_cl_smeen, re_score_rf_cl_smeen],
    "KNN": [ac_score_k_nn_smeen, f1_score_k_nn_smeen, pr_score_k_nn_smeen, re_score_k_nn_smeen],
    "XGBClassifier" : [ac_score_xgb_smeen, f1_score_xgb_smeen, pr_score_xgb_smeen, re_score_xgb_smeen]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier_smeen

"""# Methods of Combine Resampling"""

# Without oversampling for comparing
table_classifier

table_classifier_smt

table_classifier_smeen

