# -*- coding: utf-8 -*-
"""Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161iuIWVUnszP2vFD_NnAt-U6xpXi-Key
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

df

df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']].dropna()
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

df

X = df.drop('Survived', axis=1)
y = df['Survived']

df.select_dtypes(include="number").corr()

corr = X.corrwith(y).abs().sort_values(ascending=False)
print(corr)
features = corr.head(2).index.tolist()
print(f"\nSelected: {features}")

X_2d = X[features]
X_train, X_test, y_train, y_test = train_test_split(X_2d, y, test_size=0.3, random_state=42)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

h = 0.02
x_min, x_max = X_2d.iloc[:, 0].min() - 1, X_2d.iloc[:, 0].max() + 1
y_min, y_max = X_2d.iloc[:, 1].min() - 1, X_2d.iloc[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
Z = model.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

plt.figure(figsize=(10, 6))
plt.contourf(xx, yy, Z, alpha=0.3)
plt.scatter(X_2d.iloc[:, 0], X_2d.iloc[:, 1], c=y, edgecolors='k')
plt.xlabel(features[0])
plt.ylabel(features[1])
plt.title('Decision Boundary')
plt.show()

print(f"\nТочность: {accuracy_score(y_test, model.predict(X_test)):.3f}")

X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X, y, test_size=0.3, random_state=42)
# Геперпар для не допустить оверфит - параметрвы регуляризации
params = {
    'max_depth': range(1, 21),
    'min_samples_split': range(2, 51, 2), # Мин образцов для деления узла
    'min_samples_leaf': range(1, 31), # Мин образцов на листе
    'min_weight_fraction_leaf': np.linspace(0, 0.5, 20), # мин доля обр на листе
    'max_features': range(1, X.shape[1] + 1), # Сколько фич исп для разделения
    'max_leaf_nodes': range(2, 51, 2), # макс конечных узлов
    'min_impurity_decrease': np.linspace(0, 0.01, 20) # мин улучшение для разделения - мин джини индекс
}

for param_name, param_values in params.items():
    acc = []
    for val in param_values:
        m = DecisionTreeClassifier(**{param_name: val}, random_state=42)
        m.fit(X_train_full, y_train_full)
        acc.append(accuracy_score(y_test_full, m.predict(X_test_full)))

    plt.figure(figsize=(8, 4))
    plt.plot(param_values, acc, marker='o')
    plt.xlabel(param_name)
    plt.ylabel('Accuracy')
    plt.title(f'{param_name}')
    plt.grid(True, alpha=0.3)
    plt.show()

best = DecisionTreeClassifier(max_depth=2, min_samples_split=16, random_state=42)
best.fit(X_train_full, y_train_full)
print(f"\nФинальная точность: {accuracy_score(y_test_full, best.predict(X_test_full)):.3f}")

plt.figure(figsize=(20, 10))
plot_tree(best, feature_names=X.columns, class_names=['0', '1'], filled=True)
plt.show()

