# -*- coding: utf-8 -*-
"""Feature Engenireening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12x3D0rjEMKAxbn8Cov01ShuxxBOpHjj3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Pokemon.csv")

df

df.columns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression

df = df.drop("#", axis = 1)

df

df["Type 2"].value_counts(), df["Type 1"].value_counts()

df["Name"].value_counts()

df.shape

df = df.drop("Name", axis=1)

le = LabelEncoder()
df["Legendary"] = le.fit_transform(df["Legendary"])

from sklearn.preprocessing import TargetEncoder

te_columns = ['Type 1', 'Type 2']
te = TargetEncoder()
df[te_columns] = te.fit_transform(df[te_columns], df[["Legendary"]])

df

from sklearn.model_selection import train_test_split

x = df.drop("Legendary", axis=1)
y = df["Legendary"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=14)

from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ("scaled", StandardScaler()),
    ("LogisticRegression", LogisticRegression())
])

pipe.fit(x_train, y_train)
prediction = pipe.predict(x_test)

prediction

from sklearn.metrics import accuracy_score, f1_score

accuracy_score(y_test, prediction)

!pip install imperio

from imperio import ZCATransformer

zca = ZCATransformer()
zca.fit(x_train, y_train)
zca_transformed = zca.transform(x_test)

zca_transformed

plt.figure(figsize=(6,6))
plt.scatter(zca_transformed[:, 0], zca_transformed[:, 1], alpha=0.4, label="ZCA")
plt.legend()
plt.show()

df_1 = pd.read_csv("/content/avocado.csv")

df_1

df_1.columns

df_1 = df_1.drop("Unnamed: 0", axis=1)

df_1["region"].value_counts()

df_1["Date"] = pd.to_datetime(df_1["Date"])

df_1["day_of_year"] = df_1["Date"].dt.dayofyear

df_1["Date_sin"] = np.sin(2 * np.pi * df_1["day_of_year"] / 366)
df_1["Date_cos"] = np.cos(2 * np.pi * df_1["day_of_year"] / 366)

df_1 = df_1.drop("Date", axis=1)

df_1

from sklearn.preprocessing import TargetEncoder

te_columns = ["region"]
te = TargetEncoder()
df_1[te_columns] = te.fit_transform(df_1[te_columns], df_1["AveragePrice"])

df_1

df_1

df_1 = df_1.drop(["day_of_year"], axis=1)

df_1 = df_1.drop(["4046", "4225", "4770"], axis=1)

df_1

df_1 = df_1.drop(["Total Bags", "Small Bags", "Large Bags", "XLarge Bags", "Total Volume"], axis=1)

df_1 = pd.get_dummies(df_1, columns=["type", ], dtype=int, sparse=True)

df_1

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
df_1["year"] = mms.fit_transform(df_1[["year"]])

df_1

df_1 = df_1.drop(["Date_sin", "Date_cos"], axis=1)

df_1

x = df_1.drop("AveragePrice", axis=1)
y = df_1["AveragePrice"]

x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(x, y, test_size=0.3, random_state=14)

from imperio import BoxCoxTransformer
from sklearn.ensemble import RandomForestRegressor

pipe_1 = Pipeline([
    ('standartscaler', StandardScaler()),
    ("kNN", RandomForestRegressor(n_estimators=100))
])

pipe_1.fit(x_train_1, y_train_1)
prediction_1 = pipe_1.predict(x_test_1)

print(x_train_1.dtypes)

