# -*- coding: utf-8 -*-
"""GMM, Kmeans, DBSCAN, Agglomerative Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147bNwROshCmfY25cCN-GKJ_EW0JSROTN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Wine.csv")

df_features = pd.read_csv("/content/marketing_campaign.csv", sep = "\t", index_col="ID")

df_features

df_2 = pd.read_csv("/content/marketing_campaign.csv", sep = "\t", index_col="ID")
df_2

df

df.isna().sum()

df.info()

df.shape

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

X = df.values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

scores = []
K = range(2, 11)

for k in K:
    gmm = GaussianMixture(n_components=k, random_state=42)
    labels = gmm.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores.append(score)

plt.plot(K, scores, marker='o')
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette score")
plt.title("Silhouette score for GMM")
plt.show()

from sklearn.cluster import KMeans

scores_kmeans = []
K = range(2, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores_kmeans.append(score)

plt.plot(K, scores_kmeans, marker='o')
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette score")
plt.title("Silhouette score for KMeans")
plt.show()

k_gmm = 3
k_kmeans = 3

gmm = GaussianMixture(
    n_components=k_gmm,
    random_state=42
)

labels_gmm = gmm.fit_predict(X_pca)

kmeans = KMeans(
    n_clusters=k_kmeans,
    random_state=42,
    n_init=10
)

labels_kmeans = kmeans.fit_predict(X_pca)

labels_kmeans

labels_gmm

df['Cluster_KMeans'] = labels_kmeans
df['Cluster_GMM'] = labels_gmm

centroids_kmeans = kmeans.cluster_centers_

df_kmeans_means = pd.DataFrame(
    centroids_kmeans,
    columns=['feature1', 'feature2']
)

df_kmeans_means.index = ['cluster 1', 'cluster 2', 'cluster 3']

df_kmeans_means

centroids_gmm = gmm.means_

df_gmm_means = pd.DataFrame(
    centroids_gmm,
    columns=['feature1', 'feature2']
)

df_gmm_means.index = ['cluster 1', 'cluster 2', 'cluster 3']

df_gmm_means

df_2

df_2.info()

df_2["Education"].value_counts()
df_2 = pd.get_dummies(df_2, columns=["Education", "Marital_Status"], dtype=int, sparse=True)

df_2

df_2["Dt_Customer"].value_counts()

df_2

df_2["Dt_Customer"].value_counts()

x = df_2.values

from sklearn.preprocessing import StandardScaler, MinMaxScaler

sts_cols = ["Income", "Recency", "MntWines", "MntFruits",	"MntMeatProducts", "MntFishProducts", "MntSweetProducts", "MntGoldProds", "NumDealsPurchases",	"NumWebPurchases",	"NumCatalogPurchases",	"NumStorePurchases",	"NumWebVisitsMonth"]

sts = StandardScaler()
df_2[sts_cols] = sts.fit_transform(df_2[sts_cols])

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
df_2[["Year_Birth"]] = mms.fit_transform(df_2[["Year_Birth"]])

df_2

df_2["Dt_Customer"] = pd.to_datetime(df_2["Dt_Customer"], dayfirst=True)

df_2["day_of_year"] = df_2["Dt_Customer"].dt.dayofyear

df_2["day_sin"] = np.sin(2 * np.pi * df_2["day_of_year"] / 366)
df_2["day_cos"] = np.cos(2 * np.pi * df_2["day_of_year"] / 366)

df_2 = df_2.drop("Dt_Customer", axis=1)

df_2.info()

from sklearn.impute import KNNImputer

df = df.select_dtypes("number")
cols = df_2.columns
idx = df_2.index
knn = KNNImputer(n_neighbors=5)
arr = knn.fit_transform(df_2)
df_2 = pd.DataFrame(arr, columns=cols, index=idx)

df_2

df_2.isna().sum()

df_2

from sklearn.cluster import KMeans

scores_kmeans = []
K = range(2, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(df_2)

    score = silhouette_score(df_2, labels)
    scores_kmeans.append(score)

plt.plot(K, scores_kmeans, marker="o")
plt.show()

kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

prediction_kmeans = kmeans.fit_predict(df_2)

# PCA для визуализации - сн6изить размерность с 20Д до 2Д + среднее значение для колонки в засимости от кластера.
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_2)
plt.scatter(df_pca[:,0], df_pca[:,1], c=prediction_kmeans)
plt.title("Clusters with PCA")
plt.show()

plt.scatter(df_2.iloc[:,0], df_2.iloc[:,1], c=prediction_kmeans)
plt.show()

# нтрепритация кластеров
df_2['cluster'] = prediction_kmeans
cluster_means = df_2.groupby('cluster').mean()
print(cluster_means)

# grid для зависимости каждой(наиболее важн) колонки, бокс плот значение соответст каждому кластеру, что помогает интерпретировать.
features = df_2.drop(columns=['cluster']).columns

plt.figure(figsize=(12,8))

for i, col in enumerate(features):
    plt.subplot(7,7,i+1)
    sns.boxplot(x='cluster', y=col, data=df_2)

plt.tight_layout()
plt.show()

from sklearn.cluster import DBSCAN

scores_dbscan = []

eps_values = np.arange(0.5, 5, 0.2)

for eps in eps_values:

    dbscan = DBSCAN(eps=eps, min_samples=5)
    labels = dbscan.fit_predict(df_2)

    if len(set(labels)) > 1 and -1 not in set(labels):
        score = silhouette_score(df_2, labels)
        scores_dbscan.append(score)
    else:
        scores_dbscan.append(-1)

plt.plot(eps_values, scores_dbscan, marker="o")
plt.show()

dbscan = DBSCAN(
    eps=0.5,
    min_samples=5
)

prediction_dbscan = dbscan.fit_predict(df_2)

pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_2)
plt.scatter(df_pca[:,0], df_pca[:,1], c=prediction_dbscan)
plt.title("Clusters with PCA")
plt.show()

plt.scatter(df_2.iloc[:,0], df_2.iloc[:,1], c=prediction_dbscan)
plt.show()

# нтрепритация кластеров
df_2['cluster'] = prediction_dbscan
cluster_means = df_2.groupby('cluster').mean()
print(cluster_means)

from sklearn.cluster import AgglomerativeClustering

scores_agg = []
K = range(2, 11)

for k in K:

    agg = AgglomerativeClustering(n_clusters=k)
    labels = agg.fit_predict(df_2)

    score = silhouette_score(df_2, labels)
    scores_agg.append(score)

plt.plot(K, scores_agg, marker="o")
plt.show()

from scipy.cluster.hierarchy import dendrogram, linkage

agg = AgglomerativeClustering(
    n_clusters=2,
)

prediction_agg = agg.fit_predict(df_2)

Z = linkage(df_2, method='ward')

plt.figure(figsize=(8,5))
dendrogram(Z)
plt.title("Dendrogram")
plt.xlabel("Objects")
plt.ylabel("Distance")
plt.show()

# нтрепритация кластеров
df_2['cluster'] = prediction_agg
cluster_means = df_2.groupby('cluster').mean()
print(cluster_means)

from sklearn.metrics import davies_bouldin_score, calinski_harabasz_score

kmeans_dbs = davies_bouldin_score(df_2, prediction_kmeans)
dbscan_dbs = "-"
agg_dbs = davies_bouldin_score(df_2, prediction_agg)

np.unique(prediction_dbscan)

kmeans_chs = calinski_harabasz_score(df_2, prediction_kmeans)
dbscan_chs = "-"
agg_chs = calinski_harabasz_score(df_2, prediction_agg)

data = {
    "davies_bouldin_score" : [kmeans_dbs, dbscan_dbs, agg_dbs],
    "calinski_harabasz_score" : [kmeans_chs, dbscan_chs, agg_chs]
}

metrics = pd.DataFrame(data)
metrics.index = ["KMeans", "DBSCAN", "Agglomerative"]

metrics

