# -*- coding: utf-8 -*-
"""GMM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147bNwROshCmfY25cCN-GKJ_EW0JSROTN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Wine.csv")

df_2 = pd.read_csv("/content/marketing_campaign.csv", sep = "\t", index_col="ID")
df_2

df

df.isna().sum()

df.info()

df.shape

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

X = df.values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

scores = []
K = range(2, 11)

for k in K:
    gmm = GaussianMixture(n_components=k, random_state=42)
    labels = gmm.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores.append(score)

plt.plot(K, scores, marker='o')
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette score")
plt.title("Silhouette score for GMM")
plt.show()

from sklearn.cluster import KMeans

scores_kmeans = []
K = range(2, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores_kmeans.append(score)

plt.plot(K, scores_kmeans, marker='o')
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette score")
plt.title("Silhouette score for KMeans")
plt.show()

k_gmm = 3
k_kmeans = 3

gmm = GaussianMixture(
    n_components=k_gmm,
    random_state=42
)

labels_gmm = gmm.fit_predict(X_pca)

kmeans = KMeans(
    n_clusters=k_kmeans,
    random_state=42,
    n_init=10
)

labels_kmeans = kmeans.fit_predict(X_pca)

labels_kmeans

labels_gmm

df['Cluster_KMeans'] = labels_kmeans
df['Cluster_GMM'] = labels_gmm

centroids_kmeans = kmeans.cluster_centers_

df_kmeans_means = pd.DataFrame(
    centroids_kmeans,
    columns=['feature1', 'feature2']
)

df_kmeans_means.index = ['cluster 1', 'cluster 2', 'cluster 3']

df_kmeans_means

centroids_gmm = gmm.means_

df_gmm_means = pd.DataFrame(
    centroids_gmm,
    columns=['feature1', 'feature2']
)

df_gmm_means.index = ['cluster 1', 'cluster 2', 'cluster 3']

df_gmm_means

