# -*- coding: utf-8 -*-
"""Memory Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1OX2pTYZzGB1qSEVNtZXdocSTAM_e0g
"""

import dask.dataframe as dd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

ddf = dd.read_csv("/content/Lichess_2013_2014_Complete.csv")

ddf

ddf.npartitions, ddf.columns.tolist()

cols = ["WhiteElo", "BlackElo", "Winner", "Termination", "Opening", "Number_of_Moves"]
ddf = ddf[cols]
ddf = ddf.dropna()

ddf.head()

for i in range(ddf.npartitions):
    print(f"\nПартиция {i}:")
    print(ddf.partitions[i].describe().compute())

grouped = ddf.groupby("Winner")[["WhiteElo", "BlackElo", "Number_of_Moves"]].mean()

termination_counts = ddf.groupby("Termination")["Winner"].count()

termination_counts.compute()

grouped.compute()

df = ddf[["WhiteElo", "BlackElo", "Number_of_Moves", "Winner"]].compute()

df

df = df[df["Winner"] != "Draw"]

X = df[["WhiteElo", "BlackElo", "Number_of_Moves"]]
y = df["Winner"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Dask Ml - применить модифицированную версию модели

classification_report(y_test, model.predict(X_test))

ddf.groupby("Winner")["Number_of_Moves"].mean().compute().plot(
    kind="bar", figsize=(8, 5),
    title="Среднее количество ходов по победителю",
    color=["steelblue", "salmon", "grey"]
)
plt.ylabel("Ходов")
plt.tight_layout()
plt.savefig("plot1.png")
plt.show()

ddf.groupby("Termination")["Winner"].count().compute().plot(
    kind="bar", figsize=(8, 5),
    title="Количество партий по типу завершения",
    color="teal"
)
plt.ylabel("Количество")
plt.tight_layout()
plt.savefig("plot2.png")
plt.show()

