# -*- coding: utf-8 -*-
"""Model Imputation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2C4sFVIpCHGkUpg_z_iuN6A7D7DjsgZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/heart (1).csv")

df

df["RestingECG"].value_counts()

df = pd.get_dummies(df, columns = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"], dtype=int, sparse=True)

df

df_without_normalization = df.copy()

from sklearn.preprocessing import StandardScaler

df.columns

ss_cols = ["Age", 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

ss = StandardScaler()
df[ss_cols] = ss.fit_transform(df[ss_cols])

df

from sklearn.model_selection import train_test_split

x = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=14)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

lr_classifier = LogisticRegression()
lr_classifier.fit(x_train, y_train)
pred_lr_classifier = lr_classifier.predict(x_test)

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

ac_score_lr_cl = accuracy_score(y_test, pred_lr_classifier)
f1_score_lr_cl = f1_score(y_test, pred_lr_classifier)
pr_score_lr_cl = precision_score(y_test, pred_lr_classifier)
re_score_lr_cl = recall_score(y_test, pred_lr_classifier)

rf_cl = RandomForestClassifier()
rf_cl.fit(x_train, y_train)
pred_rl_cl = rf_cl.predict(x_test)

ac_score_rf_cl = accuracy_score(y_test, pred_rl_cl)
f1_score_rf_cl = f1_score(y_test, pred_rl_cl)
pr_score_rf_cl = precision_score(y_test, pred_rl_cl)
re_score_rf_cl = recall_score(y_test, pred_rl_cl)

dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
pred_dt = dt.predict(x_test)

ac_score_dt = accuracy_score(y_test, pred_dt)
f1_score_dt = f1_score(y_test, pred_dt)
pr_score_dt = precision_score(y_test, pred_dt)
re_score_dt = recall_score(y_test, pred_dt)

ber_nb = BernoulliNB()
ber_nb.fit(x_train, y_train)
pred_ber_nb = ber_nb.predict(x_test)

ac_score_ber_nb = accuracy_score(y_test, pred_ber_nb)
f1_score_ber_nb = f1_score(y_test, pred_ber_nb)
pr_score_ber_nb = precision_score(y_test, pred_ber_nb)
re_score_ber_nb = recall_score(y_test, pred_ber_nb)

g_nb = GaussianNB()
g_nb.fit(x_train, y_train)
pred_g_nb = g_nb.predict(x_test)

ac_score_g_nb = accuracy_score(y_test, pred_g_nb)
f1_score_g_nb = f1_score(y_test, pred_g_nb)
pr_score_g_nb = precision_score(y_test, pred_g_nb)
re_score_g_nb = recall_score(y_test, pred_g_nb)

k_nn = KNeighborsClassifier()
k_nn.fit(x_train, y_train)
pred_k_nn = k_nn.predict(x_test)

ac_score_k_nn = accuracy_score(y_test, pred_k_nn)
f1_score_k_nn = f1_score(y_test, pred_k_nn)
pr_score_k_nn = precision_score(y_test, pred_k_nn)
re_score_k_nn = recall_score(y_test, pred_k_nn)

from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
x_train_mm = mm.fit_transform(x_train)
x_test_mm = mm.transform(x_test)

m_nb = MultinomialNB()
m_nb.fit(x_train_mm, y_train)
pred_m_nb = m_nb.predict(x_test_mm)

ac_score_m_nb = accuracy_score(y_test, pred_m_nb)
f1_score_m_nb = f1_score(y_test, pred_m_nb)
pr_score_m_nb = precision_score(y_test, pred_m_nb)
re_score_m_nb = recall_score(y_test, pred_m_nb)

table_classifier = pd.DataFrame({
    "LogisticRegression": [ac_score_lr_cl, f1_score_lr_cl, pr_score_lr_cl, re_score_lr_cl],
    "RandomForest": [ac_score_rf_cl, f1_score_rf_cl, pr_score_rf_cl, re_score_rf_cl],
    "DecisionTree": [ac_score_dt, f1_score_dt, pr_score_dt, re_score_dt],
    "BernoulliNB": [ac_score_ber_nb, f1_score_ber_nb, pr_score_ber_nb, re_score_ber_nb],
    "MultinomialNB": [ac_score_m_nb, f1_score_m_nb, pr_score_m_nb, re_score_m_nb],
    "GaussianNB": [ac_score_g_nb, f1_score_g_nb, pr_score_g_nb, re_score_g_nb],
    "KNN": [ac_score_k_nn, f1_score_k_nn, pr_score_k_nn, re_score_k_nn]
}, index=["Accuracy", "F1", "Precision", "Recall"])

table_classifier

df_reg = pd.read_csv("/content/Dataset (3).csv")

df_reg

df_reg.drop("full_model_name", axis=1)

df_reg["city"].value_counts()

df_reg["model_name"].value_counts()

!pip install category_encoders

from category_encoders import TargetEncoder

encoder = TargetEncoder()

df_reg[["brand", "model_name"]] = encoder.fit_transform(
    df_reg[["brand", "model_name"]],
    df_reg["price"]
)

df_reg

df_reg = df_reg.drop("full_model_name", axis=1)

df_reg

df_reg = pd.get_dummies(df_reg, columns=["fuel_type", "city"], dtype=int, sparse=True)

df_reg

df_reg = df_reg.drop(["Unnamed: 0", "Id"], axis=1)

from sklearn.preprocessing import StandardScaler, MinMaxScaler

df_reg

df_reg["fuel_type_CNG + 1"].value_counts()

df_reg.columns

mm = ["year"]
mms = MinMaxScaler()
df_reg[mm] = mms.fit_transform(df_reg[mm])

scaled = ["brand", "model_name", "distance_travelled(kms)", "brand_rank", "car_age", "inv_car_price", 'inv_car_dist',  'inv_brand',
       'std_invprice', 'std_invdistance_travelled', 'std_invrank', 'best_buy1',
       'best_buy2']

ss = StandardScaler()
df_reg[scaled] = ss.fit_transform(df_reg[scaled])

import numpy as np

df_reg[scaled] = df_reg[scaled].replace([np.inf, -np.inf], np.nan)

df_reg = df_reg.drop("inv_car_age", axis=1)

df_reg

x_reg = df_reg.drop("price", axis=1)
y_reg = df_reg["price"]

x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(x, y, test_size=0.3, random_state=14)

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

lr_reg = LinearRegression()
lr_reg.fit(x_train_r, y_train_r)
pred_lr_reg = lr_reg.predict(x_test_r)

from sklearn.metrics import mean_squared_error, mean_absolute_error

lr_mse = mean_squared_error(y_test_r, pred_lr_reg)
lr_mae = mean_absolute_error(y_test_r, pred_lr_reg)
lr_rmse = np.sqrt(lr_mse)

k_nn_reg = KNeighborsRegressor()
k_nn_reg.fit(x_train_r, y_train_r)
pred_k_nn_reg = k_nn_reg.predict(x_test_r)

k_nn_reg_mse = mean_squared_error(y_test_r, pred_k_nn_reg)
k_nn_reg_mae = mean_absolute_error(y_test_r, pred_k_nn_reg)
k_nn_reg_rmse = np.sqrt(k_nn_reg_mse)

rf_reg = RandomForestRegressor()
rf_reg.fit(x_train_r, y_train_r)
pred_rf_reg = rf_reg.predict(x_test_r)

rf_reg_mse = mean_squared_error(y_test_r, pred_rf_reg)
rf_reg_mae = mean_absolute_error(y_test_r, pred_rf_reg)
rf_reg_rmse = np.sqrt(rf_reg_mse)

dt_reg = DecisionTreeRegressor()
dt_reg.fit(x_train_r, y_train_r)
pred_dt_reg = dt_reg.predict(x_test_r)

dt_reg_mse = mean_squared_error(y_test_r, pred_dt_reg)
dt_reg_mae = mean_absolute_error(y_test_r, pred_dt_reg)
dt_reg_rmse = np.sqrt(dt_reg_mse)

table_regressor = pd.DataFrame({
    "LinearRegression": [lr_mse, lr_mae, lr_rmse],
    "RandomForestRegression": [rf_reg_mse, rf_reg_mae, rf_reg_rmse],
    "DecisionTreeRegression": [dt_reg_mse, dt_reg_mae, dt_reg_rmse],
    "KNNRegression": [k_nn_reg_mse, k_nn_reg_mae, k_nn_reg_rmse]
}, index=["MSE", "MAE", "RMSE"])

table_regressor

table_classifier

!pip install shap

import shap

X_background = x_train.sample(100, random_state=42)

explainer = shap.KernelExplainer(
    model=k_nn.predict_proba,
    data=X_background
)

X_test_sample = x_test.iloc[:20]

shap_values = explainer.shap_values(X_test_sample)

sv = np.array(shap_values)
print("shap_values shape:", sv.shape)
print("X_test_sample shape:", X_test_sample.shape)

if len(sv.shape) == 3:
    if sv.shape[0] == X_test_sample.shape[0]:
        shap_class_1 = sv[:, :, 1]
    else:
        shap_class_1 = sv[1]
else:
    shap_class_1 = sv

print("chosen shap_class_1 shape:", shap_class_1.shape)

shap.summary_plot(shap_class_1, X_test_sample, plot_type="bar")

shap.summary_plot(shap_class_1, X_test_sample)

exp = shap.Explanation(
    values=shap_class_1[0],
    base_values=explainer.expected_value[1],
    data=X_test_sample.iloc[0],
    feature_names=X_test_sample.columns
)

shap.plots.waterfall(exp)

exp = shap.Explanation(
    values=shap_class_1[4],
    base_values=explainer.expected_value[1],
    data=X_test_sample.iloc[4],
    feature_names=X_test_sample.columns
)

shap.plots.waterfall(exp)

shap.initjs()

shap.force_plot(
    explainer.expected_value[1],
    shap_class_1[0],
    X_test_sample.iloc[0]
)

y_pred = lr_reg.predict(x_test_r)

errors = np.abs(y_test_r - pred_lr_reg )

top_idx = np.argsort(errors)[-5:]

# SHAP с df без нормализации

df_without_normalization

x_wn = df.drop("HeartDisease", axis=1)
y_wn = df["HeartDisease"]

x_train_wn, x_test_wn, y_train_wn, y_test_wn = train_test_split(x_wn, y_wn, test_size=0.2, random_state=14)

k_nn_1 = KNeighborsClassifier()
k_nn_1.fit(x_train_wn, y_train_wn)

x_background_wm = x_train_wn.sample(100, random_state=42)

explainer_wm = shap.KernelExplainer(
    model=k_nn_1.predict_proba,
    data=x_background_wm
)

X_test_sample_wn = x_test_wn.iloc[:20]

shap_values_wn = explainer_wm.shap_values(X_test_sample_wn)

sv_wn = np.array(shap_values_wn)
print("shap_values shape:", sv_wn.shape)
print("X_test_sample shape:", X_test_sample_wn.shape)

if len(sv_wn.shape) == 3:
    if sv_wn.shape[0] == X_test_sample_wn.shape[0]:
        shap_class_1_wn = sv[:, :, 1]
    else:
        shap_class_1_wn = sv[1]
else:
    shap_class_1_wn = sv

print("chosen shap_class_1 shape:", shap_class_1_wn.shape)

shap.summary_plot(shap_class_1_wn, X_test_sample_wn, plot_type="bar")

shap.summary_plot(shap_class_1_wn, X_test_sample_wn)

exp_wn = shap.Explanation(
    values=shap_class_1_wn[0],
    base_values=explainer.expected_value[1],
    data=X_test_sample_wn.iloc[0],
    feature_names=X_test_sample_wn.columns
)

shap.plots.waterfall(exp_wn)

exp_wn = shap.Explanation(
    values=shap_class_1_wn[1],
    base_values=explainer.expected_value[1],
    data=X_test_sample_wn.iloc[1],
    feature_names=X_test_sample_wn.columns
)

shap.plots.waterfall(exp_wn)

# SHAP с вероятносной моделью

x_background_v = x_train.sample(100, random_state=14)
explainer_v = shap.KernelExplainer(
    model = lr_classifier.predict_proba,
    data = x_background_v
)

x_test_sample_v = x_test.iloc[:20]
shap_values_v = explainer_v.shap_values(x_test_sample_v)

sv_v = np.array(shap_values_v)
if len(sv_v.shape) == 3:
  if sv_v.shape[0] == x_test_sample_v.shape[0] :
    shap_class_1_v = sv_v[:, :, 1]
  else:
    shap_class_1_v = sv_v

shap.summary_plot(shap_class_1_v, x_test_sample_v, plot_type="bar")

shap.summary_plot(shap_class_1_v, x_test_sample_v)

exp_v = shap.Explanation(
    values=shap_class_1_v[0],
    base_values=explainer.expected_value[1],
    data=x_test_sample_v.iloc[0],
    feature_names=x_test_sample_v.columns
)

shap.plots.waterfall(exp_v)

exp_v = shap.Explanation(
    values=shap_class_1_v[1],
    base_values=explainer.expected_value[1],
    data=x_test_sample_v.iloc[1],
    feature_names=x_test_sample_v.columns
)

shap.plots.waterfall(exp_v)

!pip install lime

import lime
import lime.lime_tabular

x_train_r = x_train_r.reset_index(drop=True)
x_test_r = x_test_r.reset_index(drop=True)
y_test_r = y_test_r.reset_index(drop=True)

X_train_lime = x_train_r.sparse.to_dense() if hasattr(x_train_r, "sparse") else x_train_r.copy()
X_test_lime = x_test_r.sparse.to_dense() if hasattr(x_test_r, "sparse") else x_test_r.copy()

X_train_lime = pd.DataFrame(X_train_lime).astype(float)
X_test_lime = pd.DataFrame(X_test_lime).astype(float)

X_train_lime.columns = x_train_r.columns
X_test_lime.columns = x_test_r.columns
explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train_lime.to_numpy(dtype=float),
    feature_names=X_train_lime.columns.tolist(),
    mode="regression",
    verbose=True
)

y_pred = lr_reg.predict(X_test_lime)
errors = np.abs(y_test_r.to_numpy() - y_pred)
worst_idx = np.argmax(errors)

print("Worst object index:", worst_idx)
print("True value:", y_test_r.iloc[worst_idx])
print("Predicted value:", y_pred[worst_idx])
print("Absolute error:", errors[worst_idx])

row_to_explain = X_test_lime.iloc[worst_idx].to_numpy(dtype=float)

def predict_fn(x):
    x_df = pd.DataFrame(x, columns=X_train_lime.columns)
    return lr_reg.predict(x_df)

exp = explainer.explain_instance(
    row_to_explain,
    predict_fn,
    num_features=10
)

exp.show_in_notebook(show_table=True, show_all=False)

