# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbnKSH3mSfRb0AD9HotC8V3Eikclc1sB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA as sklearnPCA

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

X = df.iloc[:, 0:4].values
y = df['species']

X_std = StandardScaler().fit_transform(X)

def pca_eigenvectors(X, n_components=2):
    cov_matrix = np.cov(X.T)
    eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
    idx = eigen_values.argsort()[::-1]
    eigen_vectors = eigen_vectors[:, idx]
    return X.dot(eigen_vectors[:, :n_components])

def pca_svd(X, n_components=2):
    u, s, vh = np.linalg.svd(X, full_matrices=False)
    return u[:, :n_components] * s[:n_components]

X_pca_eigen = pca_eigenvectors(X_std, n_components=2)
X_pca_svd = pca_svd(X_std, n_components=2)
pca_sk = sklearnPCA(n_components=2)
X_pca_sklearn = pca_sk.fit_transform(X_std)

pca_sk = sklearnPCA(n_components=1)
X_pca_sklearn = pca_sk.fit_transform(X_std)
X_pca_sklearn

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 5))
species = df['species'].unique()
colors = ['r', 'g', 'b']

for target, color in zip(species, colors):
    indices = df['species'] == target
    ax1.scatter(X_pca_eigen[indices, 0], X_pca_eigen[indices, 1], c=color, label=target)
    ax2.scatter(X_pca_svd[indices, 0], X_pca_svd[indices, 1], c=color, label=target)
    ax3.scatter(X_pca_sklearn[indices, 0], X_pca_sklearn[indices, 1], c=color, label=target)

ax1.set_title('Scratch Eigenvectors')
ax2.set_title('Scratch SVD')
ax3.set_title('Sklearn PCA')
plt.legend()
plt.show()

from mpl_toolkits.mplot3d import Axes3D

pca_3d = sklearnPCA(n_components=3)
X_pca_3d = pca_3d.fit_transform(X_std)

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

for target, color in zip(species, colors):
    indices = df['species'] == target
    ax.scatter(X_pca_3d[indices, 0],
               X_pca_3d[indices, 1],
               X_pca_3d[indices, 2],
               c=color, label=target, s=50)

ax.set_xlabel('PC1')
ax.set_ylabel('PC2')
ax.set_zlabel('PC3')
ax.set_title('3D PCA Scatter Plot')
ax.legend()
plt.show()

pca_full = sklearnPCA(n_components=4)
pca_full.fit(X_std)

components = range(1, 5)
plt.figure(figsize=(10, 5))
plt.plot(components, pca_full.explained_variance_ratio_,
         marker='o', linestyle='-', linewidth=2, markersize=8)
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.title('Explained Variance Ratio by Component')
plt.grid(True, alpha=0.3)
plt.xticks(components)
plt.show()
# Cumulative explained varience ration

from sklearn.datasets import load_digits

digits = load_digits()
X_digits = digits.data
y_digits = digits.target

fig, axes = plt.subplots(2, 5, figsize=(10, 5))
random_indices = np.random.choice(len(X_digits), 10, replace=False)

for i, ax in enumerate(axes.flat):
    idx = random_indices[i]
    ax.imshow(digits.images[idx], cmap='binary')
    ax.set_title(f'Digit: {y_digits[idx]}')
    ax.axis('off')

plt.suptitle("10 Random Digits from Dataset")
plt.show()

scaler_digits = StandardScaler()
X_scaled_digits = scaler_digits.fit_transform(X_digits)

pca_digits = sklearnPCA(n_components=2)

X_pca_digits = pca_digits.fit_transform(X_scaled_digits)

plt.figure(figsize=(10, 8))
plt.scatter(X_pca_digits[:, 0], X_pca_digits[:, 1],
            c=y_digits, edgecolor='none', alpha=0.7,
            cmap=plt.cm.get_cmap('tab10', 10))

plt.colorbar(label='Digit value', ticks=range(10))
plt.clim(-0.5, 9.5)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('Digits Dataset projected to 2D via PCA')
plt.grid(True)
plt.show()

