# -*- coding: utf-8 -*-
"""Random Forest. ynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134Nc0TSq7bwzwOymIuCVr3iGPX4dNXFK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']].dropna()
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

X = df.drop('Survived', axis=1)
y = df['Survived']

df

df.select_dtypes(include="number").corr()

corr = X.corrwith(y).abs().sort_values(ascending=False)
features = corr.head(2).index.tolist()
features

X_2d = X[features]
X_train, X_test, y_train, y_test = train_test_split(X_2d, y, test_size=0.3, random_state=42)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

def plot_boundary(model, X, y, title):
    h = 0.02
    x_min, x_max = X.iloc[:, 0].min() - 1, X.iloc[:, 0].max() + 1
    y_min, y_max = X.iloc[:, 1].min() - 1, X.iloc[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=y, edgecolors='k')
    plt.xlabel(features[0])
    plt.ylabel(features[1])
    plt.title(title)

fig = plt.figure(figsize=(14, 10))

plt.subplot(2, 2, 1)
plot_boundary(dt, X_2d, y, 'Decision Tree')

plt.subplot(2, 2, 2)
plot_boundary(rf, X_2d, y, 'Random Forest')

ax = fig.add_subplot(2, 2, 3, projection='3d')
ax.scatter(X_2d[:, 0], X_2d[:, 1], y, c=y)
ax.set_title('3D Plot')

plt.tight_layout()
plt.show()

# 3d , третья ось кол-о точек + DF на осн континуе фич

dt_acc = accuracy_score(y_test, dt.predict(X_test))
rf_acc = accuracy_score(y_test, rf.predict(X_test))
dt_acc, rf_acc

X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X, y, test_size=0.3, random_state=42)

params = {
    'max_depth': range(1, 21),
    'min_samples_split': range(2, 51, 2),
    'min_samples_leaf': range(1, 31),
    'min_weight_fraction_leaf': np.linspace(0, 0.5, 20),
    'max_features': range(1, X.shape[1] + 1),
    'max_leaf_nodes': range(2, 51, 2),
    'min_impurity_decrease': np.linspace(0, 0.01, 20)
}

best_params = {}

for param_name, param_values in params.items():
    acc = []
    for val in param_values:
        m = RandomForestClassifier(**{param_name: val}, random_state=42, n_estimators=100)
        m.fit(X_train_full, y_train_full)
        acc.append(accuracy_score(y_test_full, m.predict(X_test_full)))

    plt.figure(figsize=(8, 4))
    plt.plot(param_values, acc, marker='o')
    plt.xlabel(param_name)
    plt.ylabel('Accuracy')
    plt.title(f'Random Forest - {param_name}')
    plt.grid(True, alpha=0.3)
    plt.show()

    best_val = list(param_values)[np.argmax(acc)]
    best_params[param_name] = best_val
    print(f"{param_name}: лучшее = {best_val}, accuracy = {max(acc):.3f}")

best_rf = RandomForestClassifier(
    max_depth=best_params['max_depth'],
    min_samples_split=4,
    random_state=42,
    n_estimators=100
)
best_rf.fit(X_train_full, y_train_full) # добавить лучшие гиперпараметры + акуреси посмотреть + график по влеянию гиперпараметров вместе
# Grid search - concept ML

importance = pd.DataFrame({
    'feature': X.columns,
    'importance': best_rf.feature_importances_
}).sort_values('importance', ascending=False)

print("\nВажность признаков:")
print(importance)

plt.figure(figsize=(8, 5))
plt.barh(importance['feature'], importance['importance'])
plt.xlabel('Importance')
plt.title('Feature Importance in Random Forest')
plt.tight_layout()
plt.show()