# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC7BRvbMpIgdB2RONa2cPRvJIE7s3kXe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/bodyPerformance (1).csv")

df

df["class"].value_counts()

df["gender"] = df["gender"].replace({"M":0, "F":1})

df

df_sts = df.copy()
df_mms = df.copy()
df_mas = df.copy()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from sklearn.preprocessing import LabelEncoder

x_sts = df_sts.drop("class", axis = 1)
y = df["class"]
le = LabelEncoder()
y_sts = le.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x_sts, y_sts, test_size=0.2, random_state=42)

sts = StandardScaler()
x_train_sts = sts.fit_transform(x_train)
x_test_sts = sts.transform(x_test)

svc = SVC()
svc.fit(x_train_sts, y_train)
prediction_sts = svc.predict(x_test_sts)

prediction_sts

from sklearn.metrics import accuracy_score

as_sts = accuracy_score(y_test, prediction_sts)
as_sts

from sklearn.preprocessing import MinMaxScaler

x_mms = df_mms.drop("class", axis=1)
y_mms = df_mms["class"]
le = LabelEncoder()
y_mms = le.fit_transform(y_mms)
x_train_m, x_test_m, y_train_m, y_test_m = train_test_split(x_mms, y_mms, test_size=0.2, random_state=42)

mms = MinMaxScaler()
x_train_m = mms.fit_transform(x_train_m)
x_test_m = mms.transform(x_test_m)

svc_2 = SVC()
svc_2.fit(x_train_m, y_train_m)
prediction_mms = svc_2.predict(x_test_m)

prediction_mms

as_mms = accuracy_score(y_test_m, prediction_mms)
as_mms

from sklearn.preprocessing import MaxAbsScaler

x_mas = df_mas.drop("class", axis=1)
y_mas = df_mas["class"]
le = LabelEncoder()
y_mas = le.fit_transform(y_mas)

x_train_ma, x_test_ma, y_train_ma, y_test_ma = train_test_split(x_mas, y_mas, test_size=0.2, random_state=42)

mas = MaxAbsScaler()

x_train_ma = mas.fit_transform(x_train_ma)
x_test_ma = mas.transform(x_test_ma)

svc_mas = SVC()
svc_mas.fit(x_train_ma, y_train_ma)
prediction_mas = svc_mas.predict(x_test_ma)

prediction_mas

as_mas = accuracy_score(y_test_ma, prediction_mas)
as_mas

df

x =df.drop("class", axis=1)
y = df["class"]
le = LabelEncoder()
y = le.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

svc_initial = SVC()
svc_initial.fit(x_train, y_train)
prediction_initial = svc_initial.predict(x_test)

prediction_initial

as_initial = accuracy_score(prediction_initial, y_test)
as_initial

results = pd.DataFrame({
    "Initial" : [as_initial],
    "standard scaler" : [as_sts],
    "min max scaler" : [as_mms],
    "max abs scaler" : [as_mas]
})
results

"""# 2

"""

df

x_train, x_test, y_train, y_test

from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ("svm", SVC())
])

from sklearn.model_selection import GridSearchCV

grid = {
    "svm__kernel": ["linear", "poly", "rbf", "sigmoid"],
    "svm__C": [0.1, 1, 10], # мисклассиф от 10 самое строгое до 0.1
    "svm__gamma": ["scale", "auto"]
}

grid_m = GridSearchCV(
    estimator=pipe,
    param_grid=grid,
    cv=5,
    scoring="f1_weighted",
    n_jobs=-1
)

# y - score , x - С, линия комб разных парам, как парам с влияет на скоре

grid_m.fit(x_train, y_train)

grid_m.best_params_, grid_m.best_score_

y_pred = grid_m.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

results = pd.DataFrame(grid_m.cv_results_)

plt.figure()
plt.plot(results['mean_test_score']) //Словарь
plt.show()

print(results[['mean_test_score', 'params']])

kernel_scores = results.groupby('param_svm__kernel')['mean_test_score'].mean()

plt.figure()
plt.bar(kernel_scores.index, kernel_scores.values)
plt.show()

