# -*- coding: utf-8 -*-
"""Prep_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Vsm-upqS3tznKZMaWNN172PIc7lwvZ0

# 🚖 NYC Taxi — Business Problem

## Problem Statement
Predict `store_and_fwd_flag` — whether a trip record was held in vehicle memory
before sending to the server (Y) or sent immediately (N).

## Business Value
Understanding when server connection is unavailable helps optimize
data transmission infrastructure for taxi services.

## Dataset
- Source: NYC Taxi and Limousine Commission, 2016
- Features: pickup/dropoff location, datetime, passenger count, trip duration
- Target: store_and_fwd_flag (binary classification)
'''
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, cross_validate, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, ConfusionMatrixDisplay, RocCurveDisplay
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

train = pd.read_csv("/content/train.csv")
test  = pd.read_csv("/content/test.csv")

df = pd.concat([train, test], axis=0, ignore_index=True)

df.shape

df.info()

df.describe()

print(df.isnull().sum())

print(df.isnull().mean().round(4))

for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[f'{col}_was_missing'] = df[col].isnull().astype(int)
        print(f"Created indicator: {col}_was_missing")

important_cols = ['pickup_datetime', 'dropoff_datetime', 'trip_duration']
df = df.dropna(subset=important_cols)

# Imputation
for col in df.select_dtypes(include=np.number).columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].median(), inplace=True)
for col in df.select_dtypes(include='object').columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

df = df.drop("id", axis=1)

# Remove duplicate
print(f"\nDuplicates found: {df.duplicated().sum()}")
df = df.drop_duplicates()

# Remove outliers
cols_to_check = ['passenger_count', 'pickup_longitude', 'pickup_latitude',
                 'dropoff_longitude', 'dropoff_latitude', 'trip_duration']

before = len(df)
for col in cols_to_check:
    Q1  = df[col].quantile(0.25)
    Q3  = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df  = df[~((df[col] < Q1 - 1.5*IQR) | (df[col] > Q3 + 1.5*IQR))]

# New Features

df['distance'] = np.sqrt(
    (df['pickup_latitude']  - df['dropoff_latitude'])**2 +
    (df['pickup_longitude'] - df['dropoff_longitude'])**2
)

df['speed'] = df['distance'] / (df['trip_duration'] / 3600)

df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])
for col, period in [('hour', 24), ('dayofweek', 7), ('month', 12)]:
    val = getattr(df['pickup_datetime'].dt, col)
    df[f'pickup_{col}_sin'] = np.sin(2 * np.pi * val / period)
    df[f'pickup_{col}_cos'] = np.cos(2 * np.pi * val / period)
df = df.drop('pickup_datetime', axis=1)

df['dropoff_datetime'] = pd.to_datetime(df['dropoff_datetime'])
for col, period in [('hour', 24), ('dayofweek', 7), ('month', 12)]:
    val = getattr(df['dropoff_datetime'].dt, col)
    df[f'dropoff_{col}_sin'] = np.sin(2 * np.pi * val / period)
    df[f'dropoff_{col}_cos'] = np.cos(2 * np.pi * val / period)
df = df.drop('dropoff_datetime', axis=1)

le = LabelEncoder()
df['store_and_fwd_flag'] = le.fit_transform(df['store_and_fwd_flag'])

"""EDA"""

df[['trip_duration', 'distance', 'speed', 'passenger_count']].hist(
    figsize=(12, 8), bins=40, color='steelblue', edgecolor='black')
plt.suptitle('Feature Distributions', fontsize=14)
plt.tight_layout()
plt.show()

sns.boxplot(data=df[['trip_duration', 'distance', 'speed']])
plt.title('Boxplots — Numeric Features')
plt.show()

sns.scatterplot(data=df.sample(5000, random_state=14),
                x='distance', y='trip_duration', alpha=0.3)
plt.title('Distance vs Trip Duration')
plt.show()

corr = df.corr()
plt.figure(figsize=(18, 14))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.tight_layout()
plt.show()

target = 'store_and_fwd_flag'
correlations = df.corr()[target].drop(target).sort_values()
correlations.plot(kind='barh', figsize=(10, 8), color='coral', edgecolor='black')
plt.title('Pearson Correlation with Target')
plt.axvline(x=0.05,  color='r', linestyle='--', label='+0.05 threshold')
plt.axvline(x=-0.05, color='r', linestyle='--', label='-0.05 threshold')
plt.legend()
plt.tight_layout()
plt.show()

to_drop = set()
for i in range(len(corr.columns)):
    for j in range(i+1, len(corr.columns)):
        if abs(corr.iloc[i, j]) > 0.95:
            to_drop.add(corr.columns[j])

to_drop.discard(target)
print(f"\nMulticollinear columns removed: {to_drop}")
df = df.drop(columns=to_drop)

df

# train_test_split turn
x = df.drop(target, axis=1)
y = df[target]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=14)

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=14),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=14),
}

split_results = {}
for name, model in models.items():
    pipe = ImbPipeline([
        ('scaler', StandardScaler()),
        ('smote',  BorderlineSMOTE(random_state=14)),
        ('pca',    PCA(n_components=0.95)),
        ('model',  model)
    ])

    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)

    split_results[name] = {
        'pipeline':  pipe,
        'Accuracy':  accuracy_score(y_test, y_pred),
        'F1':        f1_score(y_test, y_pred, average='weighted'),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall':    recall_score(y_test, y_pred, average='weighted')
    }

split_df = pd.DataFrame({
    k: {m: v for m, v in v.items() if m != 'pipeline'}
    for k, v in split_results.items()
}).T.round(4)

fig, ax = plt.subplots(figsize=(10, 3))
ax.axis('off')
tbl = ax.table(cellText=split_df.values, rowLabels=split_df.index,
               colLabels=split_df.columns, cellLoc='center', loc='center')
tbl.set_fontsize(11)
tbl.scale(1.4, 2)
plt.title('Model Comparison — Train/Test Split')
plt.show()

# Overfitting Analysis
for name in split_results:
    pipe    = split_results[name]['pipeline']
    train_s = pipe.score(x_train, y_train)
    test_s  = pipe.score(x_test,  y_test)
    status  = "⚠️  Overfitting" if train_s - test_s > 0.1 else "✅ OK"
    print(f"{name:25s}: Train {train_s:.4f} | Test {test_s:.4f} | {status}")

# Best model
best_name = split_df['F1'].idxmax()
best_pipe = split_results[best_name]['pipeline']
print(f"\n🏆 Best model by F1: {best_name}")

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
ConfusionMatrixDisplay.from_estimator(best_pipe, x_test, y_test, ax=axes[0])
axes[0].set_title(f'Confusion Matrix — {best_name}')
RocCurveDisplay.from_estimator(best_pipe, x_test, y_test, ax=axes[1])
axes[1].set_title(f'ROC Curve — {best_name}')
plt.tight_layout()
plt.show()

# Cross-Validation turn
x_full = df.drop(target, axis=1)
y_full = df[target]

cv_results = {}
for name, model in models.items():
    pipe = ImbPipeline([
        ('scaler', StandardScaler()),
        ('smote',  BorderlineSMOTE(random_state=14)),
        ('pca',    PCA(n_components=0.95)),
        ('model',  model)
    ])

    scores = cross_validate(
        pipe, x_full, y_full,
        cv=5,
        scoring={
            'accuracy':  'accuracy',
            'f1':        'f1_weighted',
            'precision': 'precision_weighted',
            'recall':    'recall_weighted'
        },
        n_jobs=-1
    )
    cv_results[name] = {
        'Accuracy':  scores['test_accuracy'].mean().round(4),
        'F1':        scores['test_f1'].mean().round(4),
        'Precision': scores['test_precision'].mean().round(4),
        'Recall':    scores['test_recall'].mean().round(4)
    }
    print(f"{name} CV done")

cv_df = pd.DataFrame(cv_results).T.round(4)

# Comparison
comparison = pd.DataFrame({
    'F1 Split': split_df['F1'],
    'F1 CV':    cv_df['F1'],
    'Diff':     (split_df['F1'] - cv_df['F1']).abs().round(4)
})
print("\n=== F1 Comparison: Split vs CV ===")
print(comparison)

comparison[['F1 Split', 'F1 CV']].plot(
    kind='bar', figsize=(8, 5),
    color=['steelblue', 'coral'], edgecolor='black')
plt.title('F1 Score: Train/Test Split vs Cross-Validation')
plt.ylabel('F1 Score')
plt.xticks(rotation=15)
plt.legend()
plt.tight_layout()
plt.show()

# Hyperparameter Tuning for the best model
param_grid = {
    'pca__n_components':        [0.90, 0.95],
    'model__n_estimators':      [50, 100],
    'model__max_depth':         [5, 10, None],
    'model__min_samples_split': [2, 5]
}

tuned_pipe = ImbPipeline([
    ('scaler', StandardScaler()),
    ('smote',  BorderlineSMOTE(random_state=14)),
    ('pca',    PCA()),
    ('model',  RandomForestClassifier(random_state=14))
])

grid = RandomizedSearchCV(
    tuned_pipe, param_grid,
    n_iter=10, cv=3,
    scoring='f1_weighted',
    n_jobs=-1, random_state=14, verbose=1
)
grid.fit(x_train, y_train)
grid_prediction = grid.predict(x_test)

tabe_ht_bm = {
    "accuracy_score" : accuracy_score(y_test, grid_prediction),
    "f1_scores" : f1_score(y_test, grid_prediction),
    "recall" : recall_score(y_test, grid_prediction),
    "precition" : rprecition_score(y_test, grid_prediction)
}

tabe_ht_bm

"""# ⚖️ Ethical Considerations

## Data Privacy
- The dataset contains GPS coordinates — sensitive personal data of passengers
- Data is partially anonymized (no names), but routes may reveal home/work locations

## Model Fairness
- The model should not discriminate based on city district or vendor
- vendor_id should not be a proxy for service quality

## Data Usage
- Data used for educational purposes only
- Production deployment must comply with:
  * GDPR (EU passengers)
  * NYC local privacy laws

## Security
- GPS data must not be accessible to third parties
- The model must not be used for passenger surveillance
"""

